### ISSUE TITLE
Deployment (not an real issue more of a question)

### ISSUE THREAD

**Issue by ModernAmusements** [johannschopplich/kirby-vue-lightkit#1]
Dear Mr Schopplich, 

i really like what you did there and i am enjoy working with your starterkit! Really Great Work!

Im about to deploy my website but i seem to be unable to get the app up a running on Vercel?

Could you please provide some additional information on deployment?

Where did you deploy the apps and did you use hooks?

Cheers Shady 

of course i will compensate your work :)

**Comment by johannschopplich** [comment]
Hi Shady, glad to hear you're enjoying my starter kit!

Unfortunately, you won't be able to deploy to Vercel, since the service is targeting Node-environments (if I'm not mistaken) just like Netlify etc. You will have to run PHP on the server, which they do not provide.

See https://github.com/johannschopplich/kirby-vue3-starterkit/issues/37 for more information on deplyoment. Hope that helps and good luck!

**Comment by ModernAmusements** [comment]
Hi Johann! You are right i didnt think of that at all! I have switched to digital ocean and forge. Thank you for your help
